configfile: "config/snakemake_config.yaml"


rule all:
    input:
        # "data/rawdata/bids/3T/code/bidscoin/fixmeta.log",
        "data/derivatives/3T/freesurfer/MP2RAGE_qR1_pksUnit_stats.tsv",
        "data/derivatives/3T/freesurfer/MP2RAGE_qT1_msUnit_stats.tsv",
        "data/derivatives/3T/freesurfer/ihmt_stats.done",
        "data/derivatives/3T/MP2RAGE/MP2RAGE_to_ihmt.done",
        "data/derivatives/3T/ihmt/ihmt_to_MP2RAGE.done",
        "data/derivatives/3T/freesurfer/MPM_stats.done",
        "data/derivatives/3T/MP2RAGE/MP2RAGE_to_MPM.done",
        "data/derivatives/3T/MPM/MPM_to_MP2RAGE.done",
        "data/derivatives/3T/freesurfer/dwi_stats.done",
        "data/derivatives/3T/MP2RAGE/MP2RAGE_to_DWI.done",
        "data/derivatives/3T/MPM/DWI_to_MP2RAGE.done",
        "data/derivatives/3T/QSM/derivatives/qsmxt/"


include: "rules/B1map.smk"
include: "rules/bidsify.smk"
include: "rules/DWI.smk"
include: "rules/ihMT.smk"
include: "rules/MP2RAGE.smk"
include: "rules/multimodal_registration_segmentation.smk"
include: "rules/qMT.smk"
include: "rules/QSM.smk"